Feature/patient info
CanDIG/candig-data-portal pull request #110
Opened 2023-12-23 02:51 UTC by CourtneyGosselin

###Ticket(s)
DIG-1276

###Description
Introduce a detailed Patient Info exploration page, empowering users to effortlessly visualize patient JSON data in a concise table format. On the left, a user-friendly folder hierarchy provides easy navigation, complemented by the inclusion of ancestry table IDs seamlessly integrated into the specific table currently in view.

###Expected Behaviour
When interacting with the clinical table, users can seamlessly delve into patient clinical information by simply clicking on a row, providing an intuitive deep-dive experience.

### Screenshot PR
![image](https://github.com/CanDIG/candig-data-portal/assets/37649170/030d47f8-2903-4b11-9f25-2e7f25b237b0)

### To do/Tickets before Merging Branch
Implement a user-friendly search functionality enabling users to efficiently navigate patient or patient table data.

Types of Change(s)
 🪲 Bug fix (non-breaking change addressing an issue)
 ✨ New feature (non-breaking change introducing enhanced functionality)
 💥 Breaking change (modification that would alter existing functionality)
 
Has it been tested for:
- [ ] Prettier linter doesn't return errors
- [ ] Production branch PR browser testing: Chrome, Firefox, Edge, etc.
- [x] Locally tested
- [ ] Dev server tested
- [ ] Production tested before merging into the stable/production branch

2024-01-10 21:15 UTC, OrdiNeu requested changes
A few formatting & code changes

2024-01-10 21:15 UTC, OrdiNeu commented on src/views/clinicalGenomic/clinicalPatientView.js
> +import PatientView from './widgets/patientView';
There's a lot of linter warnings in clinicalPatientView.js and patientSidebar.js (no-unused-vars)

2024-01-10 21:15 UTC, OrdiNeu commented on src/views/clinicalGenomic/useClinicalPatientData.js
> +                console.log('RESULTS', result);
```suggestion
```

2024-01-10 21:15 UTC, OrdiNeu commented on src/views/clinicalGenomic/widgets/patientSidebar.js
> +                        className={selected === key ? `${classes.header} ${classes.selected}` : classes.header}
![image](https://github.com/CanDIG/candig-data-portal/assets/4656440/051ee404-c0f1-487e-b73a-580ea6f48abd)
While mousing over the sidebar on a button you already have selected, you get this strange looking highlighting

2024-01-10 21:15 UTC, OrdiNeu commented on src/views/clinicalGenomic/clinicalPatientView.js
> +                    {Object.entries(topLevel).map(([key, value]) => (
![image](https://github.com/CanDIG/candig-data-portal/assets/4656440/f793285f-e069-4fa6-bdd6-a94c70f529ca)
Hadn't realized this until now, but all of the information on this bottom bar is for the patient as a whole -- might be better to keep that data at the very top of the page, if that isn't too much work to change.

2024-01-10 21:15 UTC, OrdiNeu commented on src/views/clinicalGenomic/useClinicalPatientData.js
> +function useClinicalPatientData(patientId, programId) {
This function is sorta weird -- it's got useState, contexts, but does not render anything. Recommend commenting this sorta heavily to make it clear what this is all about.

2024-01-10 21:15 UTC, OrdiNeu commented on src/views/clinicalGenomic/useClinicalPatientData.js
> +    function formatKey(key) {
This function is passed around but doesn't actually depend on anything -- I recommend defining it outside of the component and importing it with { formatKey }

2024-01-10 21:15 UTC, OrdiNeu commented on src/views/clinicalGenomic/widgets/patientSidebar.js
> +    const formatKey = (key) =>
This formatKey was defined elsewhere too -- might recommend putting it somewhere else and importing it every time, if this is something super common.

2024-01-10 21:15 UTC, OrdiNeu commented on src/views/clinicalGenomic/widgets/patientSidebar.js
> +            // eslint-disable-next-line no-else-return
Is this eslint ignore still necessary? It looks correct to me now.

2024-01-10 21:15 UTC, OrdiNeu commented on src/views/clinicalGenomic/widgets/patientSidebar.js
> +    function findIdKey(obj) {
Need a comment explaining what this is about

2024-01-10 21:15 UTC, OrdiNeu commented on src/views/clinicalGenomic/widgets/patientSidebar.js
> +            <div>{createMainSidebarHeaders(sidebar)}</div>
![image](https://github.com/CanDIG/candig-data-portal/assets/4656440/43d20d39-058c-42b0-a0bb-fa3c131cc163)
The "Primary Diagnoses" highlight looks strange because of how the light blue looks further up than the main content. Recommend adding a bit of whitespace up there.

2024-01-10 21:36 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/widgets/patientSidebar.js
> +            <div>{createMainSidebarHeaders(sidebar)}</div>
Should be resolved once styled css is applied with MUI PR

2024-01-10 21:38 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/clinicalPatientView.js
> +                    {Object.entries(topLevel).map(([key, value]) => (
A redesign of this page for addition of genomic table will be coming in the next sprint or two

2024-01-10 21:39 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/widgets/patientSidebar.js
> +                        className={selected === key ? `${classes.header} ${classes.selected}` : classes.header}
Makestyle to styled change coming in MUI PR should resolve this and will be double check there

2024-01-12 20:16 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/widgets/patientSidebar.js
> +            // eslint-disable-next-line no-else-return
Was no longer necessary removed

2024-01-12 20:16 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/widgets/patientSidebar.js
> +    const formatKey = (key) =>
Pulled into utils

2024-01-12 20:16 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/useClinicalPatientData.js
> +    function formatKey(key) {
Pulled inot utils

2024-01-12 20:20 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/useClinicalPatientData.js
> +function useClinicalPatientData(patientId, programId) {
This custom hook, `useClinicalPatientData`, is for managing state and fetching clinical patient data and I have added comments. It utilizes `useState` for maintaining state variables and `useEffect` for asynchronous data fetching. The `filterNestedObject` function filters out empty arrays, objects, and values. Despite not directly rendering UI elements, this hook is used in updating the sidebar and state variables for components that leverage it.

2024-01-15 14:28 UTC, OrdiNeu commented
Can you rebase this off `develop`? There's a few merge conflicts

2024-01-15 16:49 UTC, CourtneyGosselin commented
@OrdiNeu I actually started working on rebasing right after your PR got merged in, and I'm addressing both the merge conflicts and incorporating the styled changes for patient-info. I should have it sorted out soon

2024-01-17 21:57 UTC, OrdiNeu approved these changes
Looks good!

2024-01-17 22:04 UTC, merged