DIG-1322: candig-data-portal updates: MUI, React, NPM, etc
CanDIG/candig-data-portal pull request #111
Opened 2024-01-05 18:34 UTC by OrdiNeu

## Ticket(s)

- https://candig.atlassian.net/browse/DIG-1322
- https://candig.atlassian.net/browse/DIG-1424
- https://candig.atlassian.net/browse/DIG-1425

## Description

- This should get rid of most (notably not all) of the security vulnerabilities in candig-data-portal via updating the versions of all of our npm packages. Notably, this update also completes the upgrade from muiv4 to muiv5 by getting rid of the old `useStyles` in favor of the new `styled` components.

## Expected Behaviour

- The website should work precisely the same as it did before, and look the same as well.

## To do/Tickets to be made before merging branch

- Everything more-or-less needs to be checked to make sure it all looks the same.

## Types of Change(s)

-   [x] 🪲 Bug fix (non-breaking change that fixes an issue)
-   [ ] ✨ New feature (non-breaking change that adds functionality)
-   [x] 💥 Breaking change (fix or feature that would cause existing functionality to change)

## Has it been tested for:

-   [ ] My change requires a change to the documentation
-   [ ] I have updated the documentation accordingly
-   [x] Prettier linter doesn't return errors
-   [ ] Production branch PR browser testing: Chrome, Firefox, Edge, etc.
-   [x] Locally tested
-   [ ] Dev server tested
-   [ ] Production tested when merging into stable/production branch

2024-01-05 23:15 UTC, CourtneyGosselin requested changes
Found some minor issues when trying out functionality along with some visual difference wit the update

2024-01-05 23:15 UTC, CourtneyGosselin commented on src/views/summary/summary.js
It appears the font-weight of chart titles has changed to bold see image from another PR the font-weight is set to regular. This probably changed with all the package changes. ![image](https://github.com/CanDIG/candig-data-portal/assets/37649170/95f0e772-8d93-4ebc-a474-62b07366f34b)

2024-01-05 23:15 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/widgets/sidebar.js
This error occurs when you try and use the delete all button from the below image to clear the selections
![image](https://github.com/CanDIG/candig-data-portal/assets/37649170/a007fa5c-13fc-4445-b2c7-2901ad0c769e)

![image](https://github.com/CanDIG/candig-data-portal/assets/37649170/55f9d0fa-07d8-40e0-bb46-4d83bf8694f7)

2024-01-05 23:15 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/widgets/dataVisualization.js
![image](https://github.com/CanDIG/candig-data-portal/assets/37649170/eeee6dba-2058-4d7a-86f7-d629e270f731)
Title font-weight has change to bold ir was originally a regular font.

Before:
![image](https://github.com/CanDIG/candig-data-portal/assets/37649170/79c433df-211f-41fd-9643-2368976bc91c)

2024-01-05 23:15 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/widgets/clinicalData.js
handleRowClick no longer fills in the patient tree on click.

2024-01-09 20:44 UTC, OrdiNeu commented on src/views/clinicalGenomic/widgets/clinicalData.js
Fixed in [f2c3ebe](https://github.com/CanDIG/candig-data-portal/pull/111/commits/f2c3ebeff9ffac9a0d0131c1df6e619ad4c07216)

2024-01-12 20:29 UTC, CourtneyGosselin approved these changes
LGTM

2024-01-12 20:35 UTC, merged