WIP: Feature/footer
CanDIG/candig-data-portal pull request #118
Opened 2024-01-30 17:35 UTC by CourtneyGosselin

## Ticket(s)
[DIG-1350](https://candig.atlassian.net/browse/DIG-1350)

## Description
Addition of footer to all pages that is responsive to sizing. The footer should include:
- CanDIG website - [CanDIG](https://www.distributedgenomics.ca/) 
- CanDIG GitHub - [CanDIG](https://github.com/CanDIG) 
- CanDIG Platform version number - auto populate from whichever version is deployed
- MoHCCN project link & logo - [Home](https://www.marathonofhopecancercentres.ca/)  
- Funding statement: "CanDIG Receives Funds From:"
     - [TFRI](https://www.tfri.ca/)
     - [UHN DATA](https://uhndata.io/)
     - [BCGSC](https://www.bcgsc.ca/)
     - [C3G](https://computationalgenomics.ca/)

## Screenshots (if appropriate)
### After PR

## Types of Change(s)

-   [ ] 🪲 Bug fix (non-breaking change that fixes an issue)
-   [x] ✨ New feature (non-breaking change that adds functionality)
-   [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

## Has it been tested for:

-   [ ] My change requires a change to the documentation
-   [ ] I have updated the documentation accordingly
-   [ ] Prettier linter doesn't return errors
-   [ ] Production branch PR browser testing: Chrome, Firefox, Edge, etc.
-   [x] Locally tested
-   [ ] Dev server tested
-   [ ] Production tested when merging into stable/production branch
-   [ ] [Runbook tasks](https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook) pass locally/on UHN-Dev
-   [ ] If visuals have changed, [Runbook](https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook) has been updated with new screenshots

2024-02-01 00:01 UTC, mshadbolt requested changes
pulled the branch and rebuilt stack. Looked at in Brave and Chrome - both chromium based browsers

A couple of minor bits of feedback:
* When the summary page loads on my screen, the footer is out of sight of the main page as there is a large gap under the graphs. 
![Screenshot 2024-01-31 at 3 17 46 PM](https://github.com/CanDIG/candig-data-portal/assets/13007987/defb0397-b19f-4691-ad09-fbbb00516c77)
* Maybe we could reduce this spacing so that the footer shows at the bottom of the page. So minimum spacing would be about the same as the gap at the top with the header but when there is enough space it is anchored to the bottom of the screen.
Like:
![Screenshot 2024-01-31 at 3 17 46 PM-edits](https://github.com/CanDIG/candig-data-portal/assets/13007987/33c14219-e1b6-4ad2-8720-508b25ffd14a)

* Can we change the capitalisation of the funding statement to: "CanDIG receives funds from:" (sorry I pointed this out  earlier on the shared screenshots)
* Screenshots above don't show it but I played with the CANDIG_VERSION to see that it displays and it worked for me, not sure if it could be confusing about whether this is the version of the entire stack or the data portal itself.
* Would be nice for the Candig version statement link to the relevant version of the stack? should be easy to add the given version to the url `https://github.com/CanDIG/CanDIGv2/releases/tag/v2.1.1` -> `https://github.com/CanDIG/CanDIGv2/releases/tag/${CANDIG_VERSION}` (however this is done in js that I have no clue about ) this means we do have to ensure the version is input into the .env file correctly when making stable releases to make sure the link isn't broken

2024-02-01 00:01 UTC, mshadbolt commented on src/layout/MainLayout/Footer/index.js
> +                    <p style={{ ...linkText, fontWeight: 'bold', marginBottom: '0.5em' }}>CanDIG Receives Funds from:</p>
```suggestion
                    <p style={{ ...linkText, fontWeight: 'bold', marginBottom: '0.5em' }}>CanDIG receives funds from:</p>
```

2024-02-01 21:44 UTC, CourtneyGosselin commented on src/layout/MainLayout/Footer/index.js
> +                    <p style={{ ...linkText, fontWeight: 'bold', marginBottom: '0.5em' }}>CanDIG Receives Funds from:</p>
Changes were made and responsiveness of graphs moved to their own ticket https://candig.atlassian.net/jira/software/c/projects/DIG/boards/6/backlog?selectedIssue=DIG-1470

2024-02-01 23:44 UTC, mshadbolt approved these changes
Thanks for making the updates! Happy to approve this from a visuals point of view (know nothing about the code so will leave that up to @OrdiNeu )

2024-02-05 20:28 UTC, OrdiNeu approved these changes
Looks good to me

2024-02-05 20:28 UTC, OrdiNeu commented on src/layout/MainLayout/Footer/index.js
> +const SocialsContainer = styled(Box)(({ theme }) => ({
ESLint warning
```suggestion
const SocialsContainer = styled(Box)(({ _ }) => ({
```

2024-02-05 20:28 UTC, OrdiNeu commented on src/layout/MainLayout/Footer/index.js
> +const LinkFrame = styled(Box)(({ theme }) => ({
ESLint warning
```suggestion
const LinkFrame = styled(Box)(({ _ }) => ({
```

2024-02-05 20:28 UTC, OrdiNeu commented on src/layout/MainLayout/Footer/index.js
> +const ResponsiveFooterContainer = styled('footer')(({ theme }) => ({
Could be simplified with the classNames thing that the rest of the components use, but probably not neccecssary

2024-02-05 20:28 UTC, OrdiNeu commented on src/layout/MainLayout/Footer/index.js
> +            console.log('Email copied to clipboard');
```suggestion
```

2024-02-05 20:28 UTC, OrdiNeu commented on src/layout/MainLayout/Footer/index.js
> +                        console.log('Email copied to clipboard');
```suggestion
```
NB: This is usually a mailto: redirect (I believe usually for accessibility?), but to be honest I prefer this copying

2024-02-05 20:59 UTC, CourtneyGosselin commented on src/layout/MainLayout/Footer/index.js
> +                        console.log('Email copied to clipboard');
mailto bug not working on all browsers fix for the meantime till that can be fixed for accessibility. This atleast covers dexterity issues when copying but may not be ideal for screen readers. I will add a ticket to JIRA

2024-02-05 21:00 UTC, merged