Hotfix: forfollowup dates
CanDIG/candig-data-portal pull request #131
Opened 2024-03-15 20:10 UTC by CourtneyGosselin

## Description
Dates not working for followups on patient info page added object chaining to handle undefined

## Types of Change(s)

-   [x] 🪲 Bug fix (non-breaking change that fixes an issue)
-   [ ] ✨ New feature (non-breaking change that adds functionality)
-   [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

## Has it been tested for:

-   [x] My change requires a change to the documentation of the runbook
-   [ ] I have updated the documentation accordingly
-   [x] Prettier linter doesn't return errors
-   [ ] Production branch PR browser testing: Chrome, Firefox, Edge, etc.
-   [x] Locally tested
-   [ ] Dev server tested
-   [ ] Production tested when merging into stable/production branch
-   [ ] [Runbook tasks](https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook) pass locally/on UHN-Dev
-   [ ] If visuals have changed, [Runbook](https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook) has been updated with new screenshots

2024-03-15 22:23 UTC, mshadbolt approved these changes
Looks good to me in the portal!

2024-03-18 14:34 UTC, OrdiNeu requested changes

2024-03-18 14:34 UTC, OrdiNeu commented on src/views/clinicalGenomic/widgets/clinicalData.js
> +                    if (patient?.date_resolution === 'month') {
I'm unsure about the logic here -- are we sure date_resolution will always be there? It does appear to be a "required field", but I can't find where it is set in clinical_ETL_code (outside of being imported).

2024-03-18 14:34 UTC, OrdiNeu commented on src/views/clinicalGenomic/useClinicalPatientData.js
> +                        }
```suggestion
                        if (filteredData?.date_of_death?.month_interval && filteredData?.date_of_birth?.month_interval) {
                            const ageInMonths = filteredData.date_of_death.month_interval - filteredData.date_of_birth.month_interval;
                            filteredData.age_at_death = Math.floor(ageInMonths / 12);
                            filteredData.age_at_first_diagnosis = Math.floor(-filteredData.date_of_birth.month_interval / 12);
                        } else if (filteredData?.date_of_birth?.month_interval && !filteredData?.date_of_death?.month_interval) {
                            filteredData.age_at_first_diagnosis = Math.floor(-filteredData.date_of_birth.month_interval / 12);
                        }
                        delete filteredData.date_of_death;
                        delete filteredData.date_of_birth;
```

2024-03-18 14:34 UTC, OrdiNeu commented on src/views/clinicalGenomic/useClinicalPatientData.js
> +                        }
```suggestion
                        if (filteredData?.date_of_death?.day_interval && filteredData?.date_of_birth?.day_interval) {
                            const ageInDays = filteredData.date_of_death.day_interval - filteredData.date_of_birth.day_interval;
                            filteredData.age_at_death = Math.floor(ageInDays / 365);
                            filteredData.age_at_first_diagnosis = Math.floor(-filteredData.date_of_birth.day_interval / 365);
                        } else if (filteredData?.date_of_birth?.day_interval && !filteredData?.date_of_death?.day_interval) {
                            filteredData.age_at_first_diagnosis = Math.floor(-filteredData.date_of_birth.day_interval / 365);
                        }
                        delete filteredData.date_of_death;
                        delete filteredData.date_of_birth;
```

2024-03-18 14:34 UTC, OrdiNeu commented on src/views/clinicalGenomic/useClinicalPatientData.js
> +                        }
(Refactor out the common parts to reduce duplication)

2024-03-18 14:34 UTC, OrdiNeu commented on src/views/clinicalGenomic/useClinicalPatientData.js
> +                        }
(Refactor out the common parts to reduce duplication)

2024-03-18 14:34 UTC, OrdiNeu commented on src/views/clinicalGenomic/widgets/clinicalData.js
> +                    if (patient?.date_resolution === 'month') {
Notably, if dob/dod are given but not the resolution, this will discard the data instead of inspecting it to see if we can parse it.

2024-03-18 18:19 UTC, mshadbolt approved these changes
Functioning as expected on the data portal with the latest changes

2024-03-18 20:19 UTC, OrdiNeu approved these changes
LGTM :heavy_check_mark:

2024-03-18 20:19 UTC, OrdiNeu commented on src/views/clinicalGenomic/useClinicalPatientData.js
> +                            delete filteredData.date_of_birth;
Low priority note: if neither day_interval and month_interval exist, then DOB/DOD don't get deleted. This might be intentional behaviour -- passing it forwards until a later component can make sense of it, but just a heads up

2024-03-18 20:26 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/useClinicalPatientData.js
> +                            delete filteredData.date_of_birth;
Added an else to cover this case

2024-03-18 20:31 UTC, merged