Added donor timeline on patient info page
CanDIG/candig-data-portal pull request #134
Opened 2024-03-26 17:59 UTC by lilyyangyi301

## Ticket(s)

- [DIG 1484](https://candig.atlassian.net/browse/DIG-1484)

## Description

- Added donor timeline on patient info page to show the sequence of diagnosis and treatment events using Highcharts.

## Expected Behaviour

- The timeline will change accordingly based on donor id.

## Screenshots (if appropriate)

## Types of Change(s)

-   [ ] 🪲 Bug fix (non-breaking change that fixes an issue)
-   [x] ✨ New feature (non-breaking change that adds functionality)
-   [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

## Has it been tested for:

-   [ ] My change requires a change to the documentation
-   [ ] I have updated the documentation accordingly
-   [x] Prettier linter doesn't return errors
-   [ ] Production branch PR browser testing: Chrome, Firefox, Edge, etc.
-   [x] Locally tested
-   [ ] Dev server tested
-   [ ] Production tested when merging into stable/production branch
-   [ ] [Runbook tasks](https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook) pass locally/on UHN-Dev
-   [ ] If visuals have changed, [Runbook](https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook) has been updated with new screenshots

2024-03-27 17:15 UTC, OrdiNeu commented
This PR appears to be missing a file: `timeline.js`

2024-03-27 17:36 UTC, lilyyangyi301 commented
> This PR appears to be missing a file: `timeline.js`



> This PR appears to be missing a file: `timeline.js`

![Screenshot 2024-03-27 at 1 35 36 PM](https://github.com/CanDIG/candig-data-portal/assets/75077668/e28230b9-a605-4c95-9882-7e7afb75b506)
I think it's here but don't know why it's not loading.

2024-03-27 19:11 UTC, OrdiNeu commented
Oh, I missed it. There's a lot of ESLint errors in it though -- can you fix those before I review? (To get it to load, just click the "Load diff" link)

2024-03-27 19:15 UTC, lilyyangyi301 commented
> Oh, I missed it. There's a lot of ESLint errors in it though -- can you fix those before I review? (To get it to load, just click the "Load diff" link)

Sure thing!

2024-03-27 20:50 UTC, lilyyangyi301 commented
ESLint errors are fixed,

2024-04-18 18:59 UTC, CourtneyGosselin requested changes
It all is really good I have some minor suggestions on improvements. The only real bug I see is the datagrid not using a shared state or redux between timeline and sidebar.

2024-04-18 18:59 UTC, CourtneyGosselin commented on src/utils/utils.js
> + * @param {function} setTitle - Function to set the title of the table
You mention the set states we used here howevver these parameter are not passed into your function from the componenet it is in. These should be removed from the description if they are not being used or changed to using them

2024-04-18 18:59 UTC, CourtneyGosselin commented on src/utils/utils.js
> +    const titleClick = formatKey(title);
This wording is confusing we may want to use a shared state instead of two competing values

2024-04-18 18:59 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/clinicalPatientView.js
> +
I would pull out the original setters from useClinicalPatientData and pass forward to it. This will result in shared rows, columns, title in the datagrid that the timeline can also use. Currently the data grid shows the click value if it has ever been selected based on the ternary statement

2024-04-18 18:59 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/clinicalPatientView.js
> +                    rows={clickRow.length > 0 ? clickRow : rows}
I think this will result in an error once a timeline event is clicked the clickRow will have been set and only ever show that in the datagrid vs a sidebar selection

2024-04-18 18:59 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/widgets/timeline.js
> +const colorPalette = [
colorpalette should be defined in our theme

2024-04-18 18:59 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/widgets/timeline.js
> +import { useEffect, useState } from 'react';
Your code is generally readable but you should take some time to add comments and explanations

2024-04-18 18:59 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/widgets/timeline.js
> +const generateRandomColor = () => {
Could be simplified `const generateRandomColor = () => colorPalette[Math.floor(Math.random() * colorPalette.length)];`

2024-04-18 18:59 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/widgets/timeline.js
> +const tooltipFormatter = () =>
This section can be simplified by pulling out the common parts. I haven't tested this since I am in the middle of my change but something like

```
const tooltipFormatter = () => function tooltipFormatter() {
    const boldName = `<span style="font-weight: bold">${this.name || 'Treatment'}</span><br/>`;
    const yearInAge = Math.floor(this.x / 12);
    
    const getYearInAgeText = (prefix, value) => `${prefix}: ${Math.floor(value / 12)} Year(s) Old`;
    
    const treatmentTypeText = this.treatment_type ? `Type: ${this.treatment_type}` : 'Treatment type not specified';
    
    let tooltipContent = '';

    if (this.extra_info) {
        const extraInfoText = `${this.extra_info} : ${yearInAge} Year(s) Old`;
        const missingInfoText = this.missing_info === 'Start' ? 'Start Date Missing' : 'End Date Missing';
        tooltipContent = `${boldName}${treatmentTypeText}<br/>${extraInfoText}<br/>${missingInfoText}<br/>`;
    } else if (this.start) {
        const startYearText = getYearInAgeText('Start', this.start);
        const endYearText = getYearInAgeText('End', this.end);
        
        if (this.name === 'Treatments') {
            tooltipContent = `${boldName}${startYearText}<br/>${endYearText}<br/>`;
        } else {
            tooltipContent = `${boldName}${treatmentTypeText}<br/>${startYearText}<br/>${endYearText}<br/>`;
        }
    } else {
        tooltipContent = `${boldName}${yearInAge} Year(s) Old`;
    }

    return tooltipContent;
};
```

2024-04-18 18:59 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/widgets/timeline.js
> +    const { data } = useClinicalPatientData(patientId, programId);
This can probably just be called the level above and pass data forward. This way we avoid making 2 massive katsu calls

2024-04-18 18:59 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/widgets/timeline.js
> +        const generateSeriesData = (data, path, path2, date, id, yValue, colour, namePrefix, isSingleItem, name, birthDateValue) => {
You may be able to make use of the useMemo for your seriesData 
 // Memoize series data for efficiency
 const seriesData = useMemo(() => generateCategorySeries(data, birthMonthInterval), [data, birthMonthInterval]);

2024-04-18 18:59 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/widgets/timeline.js
> +const headerFormatter = (dateResolution) =>
This might be more clear ad formatHeader() as the function name

2024-04-20 21:37 UTC, lilyyangyi301 commented on src/views/clinicalGenomic/widgets/timeline.js
> +        const generateSeriesData = (data, path, path2, date, id, yValue, colour, namePrefix, isSingleItem, name, birthDateValue) => {
Since generateSeriesData takes more than just data and birthMonthInterval, I'm not sure how I can use useMemo here

2024-04-20 21:57 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/widgets/timeline.js
> +        const generateSeriesData = (data, path, path2, date, id, yValue, colour, namePrefix, isSingleItem, name, birthDateValue) => {
I should have used a better example. I more so meant that it could be used with the series data so that there was less rerenders. A general suggestion but it can be done and looked into on a future ticket

2024-04-25 19:15 UTC, CourtneyGosselin requested changes
Just some final things

2024-04-25 19:15 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/clinicalPatientView.js
> +                    <Alert style={{ width: '50%', marginTop: '20px' }} severity="warning">
Add the variant outline to make it more obvious

2024-04-25 19:15 UTC, CourtneyGosselin commented on src/views/clinicalGenomic/widgets/timeline.js
> +                    plotLines: [
Adjust text of ploitline so that it stays behind text of the section on the left. May need to adust z-index https://api.highcharts.com/highcharts/xAxis.plotLines

2024-04-25 20:04 UTC, merged