DIG-1557 Data Portal Fixes from runbook on March 27, 2024
CanDIG/candig-data-portal pull request #135
Opened 2024-04-05 16:30 UTC by OrdiNeu

## Ticket(s)

-[DIG-1557](https://candig.atlassian.net/browse/DIG-1557)

## Description

Fixes:

- Genomic not displayed while logged in as non-user2?

- Remove one treatment = remove all treatments?

- Switch to two of the same chart, remove a chart in the middle, refresh page, suddenly a different chart is changed

- Edit runbook for genomic testing

- Tumor Registration ID -> Specimen Registration ID

- Add cohort ID to genomic results graph

- Warning: Failed prop type: Invalid prop children of type array supplied to ForwardRef(Tooltip), expected a single ReactElement.

**Does not fix**:

- Switching page size on search page clears the sidebar but doesn't clear the search results

- Sidebar bug if it is open and you reduce page size

## Related Issues (if appropriate)

- [DIG-1563](https://candig.atlassian.net/browse/DIG-1563)

## Types of Change(s)

-   [x] 🪲 Bug fix (non-breaking change that fixes an issue)
-   [ ] ✨ New feature (non-breaking change that adds functionality)
-   [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

## Has it been tested for:

-   [ ] My change requires a change to the documentation
-   [ ] I have updated the documentation accordingly
-   [x] Prettier linter doesn't return errors
-   [ ] Production branch PR browser testing: Chrome, Firefox, Edge, etc.
-   [x] Locally tested
-   [ ] Dev server tested
-   [ ] Production tested when merging into stable/production branch
-   [x] [Runbook tasks](https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook) pass locally/on UHN-Dev
-   [ ] If visuals have changed, [Runbook](https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook) has been updated with new screenshots

[DIG-1557]: https://candig.atlassian.net/browse/DIG-1557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DIG-1563]: https://candig.atlassian.net/browse/DIG-1563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-04-19 19:05 UTC, mshadbolt requested changes
The treatment sidebar selection still seems to be acting weirdly. With the new small synthetic dataset if I select 'hormonal therapy' I get DONOR_1&2, if I then add 'chemotherapy' I get an additional donor DONOR_4, then I remove 'chemotherapy', and I get all donors, 1,2,3,4,5,6

![Screenshot 2024-04-19 at 11 49 26 AM](https://github.com/CanDIG/candig-data-portal/assets/13007987/1395a60a-0041-4254-821f-bcfd54a141b9)
![Screenshot 2024-04-19 at 11 49 34 AM](https://github.com/CanDIG/candig-data-portal/assets/13007987/901cb0df-da9d-4b8d-9b6b-aae79b89f9ba)
![Screenshot 2024-04-19 at 11 49 41 AM](https://github.com/CanDIG/candig-data-portal/assets/13007987/cb7b0397-c881-478e-9419-1f93415f2f14)

- completeness issue seems fixed
- couldn't reproduce the graph change error
- can we change 'Specimen Registration ID' to 'Sample Registration ID'
- confirm can see genomic completeness per program on graph

2024-04-19 19:05 UTC, mshadbolt commented on src/views/clinicalGenomic/widgets/genomicData.js
> +        { field: 'submitter_specimen_id', headerName: 'Specimen Registration ID', minWidth: 300, sortable: false },
```suggestion
        { field: 'submitter_specimen_id', headerName: 'Sample Registration ID', minWidth: 300, sortable: false },
```

2024-04-19 20:05 UTC, OrdiNeu commented
> The treatment sidebar selection still seems to be acting weirdly. With the new small synthetic dataset if I select 'hormonal therapy' I get DONOR_1&2, if I then add 'chemotherapy' I get an additional donor DONOR_4, then I remove 'chemotherapy', and I get all donors, 1,2,3,4,5,6

Good catch -- I think I managed to fix it in [8696068](https://github.com/CanDIG/candig-data-portal/pull/135/commits/8696068d53955c522d82054b8b7178533dd77f7d) :heavy_check_mark:

2024-04-19 20:37 UTC, mshadbolt commented
Not exactly sure what triggered it. I had previously deleted all the visualisation graphs, then I tried to add the primary_site graph back and this error was thrown and I can't get the search page back
![Screenshot 2024-04-19 at 1 35 24 PM](https://github.com/CanDIG/candig-data-portal/assets/13007987/ebafdc32-3cb8-4cc2-b629-052af0a6877f)

The treatment fix seemed to be working before I did this though. Would it be better for me to make a new ticket for the error above?

2024-04-22 14:56 UTC, OrdiNeu commented
@mshadbolt 
> Maybe it freaks out if I have a filter selected that has no primary sites but try to show a graph of primary sites?

I think I got a sort-of fix working in [243b381](https://github.com/CanDIG/candig-data-portal/pull/135/commits/243b381458ea19b20083c1e458aa51a4505281e9), except it won't work if your cache is already messed up. This prevents users from invalidating their localstorage by doing the steps you've described though.

2024-04-22 17:32 UTC, mshadbolt approved these changes
LGTM!

2024-04-22 17:46 UTC, merged