Change 'cancer_type' to 'primary_site'
CanDIG/candig-data-portal pull request #144
Opened 2024-05-21 19:37 UTC by OrdiNeu

## Ticket(s)

- [DIG-1533](https://candig.atlassian.net/browse/DIG-1533)

## Description

- Changes `cancer_type_count` to `primary_site_count` internally. Requires the corresponding PRs from Katsu and Query.

## Expected Behaviour

- Nothing has changed visually, only internal variable names.

## Related Issues (if appropriate)

- 

## Types of Change(s)

-   [x] 🪲 Bug fix (non-breaking change that fixes an issue)
-   [ ] ✨ New feature (non-breaking change that adds functionality)
-   [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

## Has it been tested for:

-   [ ] My change requires a change to the documentation
-   [ ] I have updated the documentation accordingly
-   [ ] Prettier linter doesn't return errors
-   [ ] Production branch PR browser testing: Chrome, Firefox, Edge, etc.
-   [x] Locally tested
-   [ ] Dev server tested
-   [ ] Production tested when merging into stable/production branch
-   [ ] [Runbook tasks](https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook) pass locally/on UHN-Dev
-   [ ] If visuals have changed, [Runbook](https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook) has been updated with new screenshots

2024-05-27 20:02 UTC, CourtneyGosselin requested changes
It appears that the tooltips have changed and are now displaying differently, as shown in the attached picture for the map view. We should check if this issue affects other tooltips as well
![image](https://github.com/CanDIG/candig-data-portal/assets/37649170/eac216b1-de9e-45c9-abbd-34ce02af90aa)
![screencapture-candig-docker-internal-5080-clinicalGenomicSearch-2024-05-27-12_10_42](https://github.com/CanDIG/candig-data-portal/assets/37649170/5cb0a91e-94d1-4793-a647-88864e0b1f17)

On the search page where the graphs are not displaying any data because of AGGREGATRE_COUNT_THRESHOLD. Additionally, the "Attention" section is not visible for the data visualization when data is showing nothing. This is confusing because the clinical table shows data, but the graphs and patient count at the top both display 0.

2024-05-27 20:02 UTC, CourtneyGosselin commented on src/store/mcode.js
> + * NB: Unused?
We dont use this anymore it can be removed. I think we originally kept it when we were making the search page but wasn't removed once it was finished.

2024-05-28 16:55 UTC, OrdiNeu commented
> It appears that the tooltips have changed and are now displaying differently, as shown in the attached picture for the map view. We should check if this issue affects other tooltips as well

I've given it a once-over, should be fixed now.

2024-06-05 20:23 UTC, CourtneyGosselin approved these changes
LGTM once Marions bug is taken care of on CanDIGv2

2024-06-06 16:23 UTC, merged