Feature/auth page
CanDIG/candig-data-portal pull request #201
Opened 2024-12-18 22:21 UTC by OrdiNeu

## Ticket(s)

- [DIG-1857](https://candig.atlassian.net/browse/DIG-1857)

## Description 

- This allows a logged-in user to see a request access page if they are not yet in OPA, and to request access.

# Screenshots
![image](https://github.com/user-attachments/assets/d76b8eee-1cf7-4417-95c0-a36fc9c95d4f)

![image](https://github.com/user-attachments/assets/b1bd7484-2a02-4063-94d4-0b2e4be5fe1c)

## To do/Tickets to be made before merging branch

- This should be tested via https://github.com/CanDIG/candigv2-ingest/pull/147

## Types of Change(s)

-   [ ] 🪲 Bug fix (non-breaking change that fixes an issue)
-   [x] ✨ New feature (non-breaking change that adds functionality)
-   [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

## Has it been tested for:

-   [ ] My change requires a change to the documentation
-   [ ] I have updated the documentation accordingly
-   [ ] Prettier linter doesn't return errors
-   [ ] Production branch PR browser testing: Chrome, Firefox, Edge, etc.
-   [x] Locally tested
-   [ ] Dev server tested
-   [ ] Production tested when merging into stable/production branch
-   [ ] [Runbook tasks](https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook) pass locally/on UHN-Dev
-   [ ] If visuals have changed, [Runbook](https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook) has been updated with new screenshots

2024-12-18 22:55 UTC, CourtneyGosselin requested changes
I’d suggest a few minor visual changes. The shadow on the entire dialog is missing, as well as the shadow on the gray container, but these aren’t necessary if we prefer a flatter design. I’d change the pending hourglass to yellow, add 2–3em of spacing above the gray container and below the contact/request button, and adjust the hourglass padding to around 1em above and below. Finally, the dialog box should be centered within the blue main container.

I also see some linter errors some which will resolve by merging in the develop branch
![image](https://github.com/user-attachments/assets/d06905d1-dff8-4010-9fb9-586b91608bc0)

2024-12-18 22:55 UTC, CourtneyGosselin commented on src/views/pages/authentication/AuthDisplay.js
> +                        Contact
If a support email isn’t set, should we remove the contact button and advise users to reach out to their admins/your site?

2024-12-18 22:55 UTC, CourtneyGosselin commented on public/index.html
> +        <noscript>You need to enable JavaScript to run this app. <link rel="test" href="%PUBLIC_URL%/iframetest.html" /></noscript>
Did you mean to push this?

2024-12-19 15:37 UTC, OrdiNeu commented on public/index.html
> +        <noscript>You need to enable JavaScript to run this app. <link rel="test" href="%PUBLIC_URL%/iframetest.html" /></noscript>
My apologies, that was for testing something unrelated

2024-12-19 21:06 UTC, CourtneyGosselin approved these changes
LGTM just some minor linter warnings tested with user2

2024-12-19 21:09 UTC, merged