DIG-1514: An invalid chart in CustomOfflineCharts.js causes the searchpage to whitescreen.
CanDIG/candig-data-portal pull request #202
Opened 2024-12-31 21:55 UTC by OrdiNeu

## Ticket(s)

- https://candig.atlassian.net/browse/DIG-1514

## Description

- This fixes an issue where an erroneous localstorage would cause the searchpage to whitescreen. This also involves a refactor of the entire `dataVisualization.js` component, as it was a bit unwieldy to work with.

## Expected Behaviour

- No changes should be visible, although if you corrupt your localStorage into having an invalid chart type it should fix itself automatically.

## Types of Change(s)

-   [x] 🪲 Bug fix (non-breaking change that fixes an issue)
-   [ ] ✨ New feature (non-breaking change that adds functionality)
-   [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

## Has it been tested for:

-   [ ] My change requires a change to the documentation
-   [ ] I have updated the documentation accordingly
-   [ ] Prettier linter doesn't return errors
-   [ ] Production branch PR browser testing: Chrome, Firefox, Edge, etc.
-   [x] Locally tested
-   [ ] Dev server tested
-   [ ] Production tested when merging into stable/production branch
-   [ ] [Runbook tasks](https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook) pass locally/on UHN-Dev
-   [ ] If visuals have changed, [Runbook](https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook) has been updated with new screenshots

2025-01-10 20:02 UTC, CourtneyGosselin requested changes
I am encountering several errors with the data visualization component:

1. Changing chartType in local storage:
-  I tried setting one to `bars` instead of `bar` this resulted in highcharts error number 17 `missingModuleFor=bars`
- Tried changing the data to a non-existent option and got an infinite loading time

2. Changing dropdowns
- Changing the dropdown of the data or chartType resulted in an error as well. 

![image](https://github.com/user-attachments/assets/3cdd4ea6-0bf3-4781-80aa-f25ec6763c00)

Most of these resolve after page refresh.

2025-01-10 21:38 UTC, OrdiNeu commented
> I am encountering several errors with the data visualization component:
> 
>     1. Changing chartType in local storage:
> 
> 
>     * I tried setting one to `bars` instead of `bar` this resulted in highcharts error number 17 `missingModuleFor=bars`
> 
>     * Tried changing the data to a non-existent option and got an infinite loading time
> 
> 
>     2. Changing dropdowns
> 
> 
>     * Changing the dropdown of the data or chartType resulted in an error as well.
> 
> 
> ![image](https://private-user-images.githubusercontent.com/37649170/402134493-3cdd4ea6-0bf3-4781-80aa-f25ec6763c00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY1NDQxOTIsIm5iZiI6MTczNjU0Mzg5MiwicGF0aCI6Ii8zNzY0OTE3MC80MDIxMzQ0OTMtM2NkZDRlYTYtMGJmMy00NzgxLTgwYWEtZjI1ZWM2NzYzYzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDIxMTgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNWU3ZGFlYTIzZDIzMjJkZjg4M2RmYTc5NmFjNWVhYzFhMWU4YzUxNGI1YTFlZGM0YWQ3ODNmNzM1ZGQwYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.glL4Ti2Iiqa6nxOcGk7bcoRs99u925ttYEyoSNOx5Uc)
> 
> Most of these resolve after page refresh.

Should be fixed now, though after staring at my code I have no idea how it ever worked in the first place. Thanks!

2025-01-13 18:21 UTC, CourtneyGosselin requested changes
If you remove a chart, it only removes the last chart added instead of the specific one. Code now works correctly when using the dropdowns. Additionally, it works if I change the localStorage chartType to an invalid option. However, if you set it to an invalid data option, the chart enters an infinite loading state. We might want to prevent this from displaying as well. Also two linter warnings are shown

2025-01-13 20:45 UTC, OrdiNeu commented
@CourtneyGosselin 
Should be fixed now

2025-01-14 17:26 UTC, CourtneyGosselin approved these changes
LGTM!

2025-01-14 19:36 UTC, merged