WIP: Theme, screen resolution layout, api endpoints for summary page
CanDIG/candig-data-portal pull request #74
Opened 2023-03-14 22:18 UTC by CourtneyGosselin

## Description
Update the summary page to match Figma redesigns as well as update theme colouring.

## Ticket
[JIRA DIG-992](https://candig.atlassian.net/browse/DIG-992)

## Acceptance Criteria: 
- [ ] Matches Figma designs
- [ ] Correct endpoints for the summary page

2023-05-18 18:49 UTC, OrdiNeu requested changes
In addition to the code comments below, found the following errors while trying to access the frontpage. I think it may be due to this being built on older versions of federation&Katsu:

![image](https://github.com/CanDIG/candig-data-portal/assets/4656440/26a805d1-7352-4a16-9aa6-d99ac9817afd)
Failing endpoints:
- moh/v1/discovery/overview/cancer_type_count
- moh/v1/discovery/overview/patients_per_cohort
- moh/v1/discovery/overview/treatment_type_count
(these might be more katsu things? Unsure, since the latest version of Katsu is in v2/)

2023-05-18 18:49 UTC, OrdiNeu commented on src/store/api.js
> +            return {};
Prefer having a `console.log()` (or other logging statement) on failure here, as it might be unclear what is going on if the response is not ok.

2023-05-18 18:49 UTC, OrdiNeu commented on src/views/summary/CustomOfflineChart.js
> +            });
It's more idiomatic to use forEach() here -- `.map()` is for when you care about the return value. It also lets us use the built-in iterator, like so:
```suggestion

            Object.keys(dataObject).forEach((key, i) => {
                categories.push(key);
                Object.keys(dataObject[key]).forEach((cohort) => {
                    if (!data.has(cohort)) {
                        data.set(cohort, new Array(Object.keys(dataObject).length).fill(0));
                    }
                    data.get(cohort).splice(i, 1, dataObject[key][cohort]);
                });
            });
```
I haven't yet tested the above, but something along these lines might be easier to read.

2023-05-18 18:49 UTC, OrdiNeu commented on src/views/summary/summary.js
> +        }, 9250);
Unsure about chaining fetches with constant timeouts like this. This code is due to federation causing errors when you try to give it too many requests at once, right? I wonder if we could instead chain `fetchData` calls via  `.then()`, and retrying (with a timeout) if it fails? That way, if federation becomes _really_ slow, this code would still be able to load without failure.

2023-05-18 19:14 UTC, CourtneyGosselin commented on src/views/summary/summary.js
> +        }, 9250);
Yes, I originally had it as an async call, but it causes gateway timeout errors. Then, I just one after the other, which caused the same. So yes, this is a bandaid fix just to get the calls to complete I can modify it

2023-05-23 19:33 UTC, OrdiNeu commented
@yavyx 
Per end-of-sprint demo discussion

2023-06-06 20:23 UTC, OrdiNeu approved these changes

2023-06-06 20:33 UTC, merged