Custodian page
CanDIG/candig-data-portal pull request #94
Opened 2023-08-10 18:09 UTC by justin-ys

## Ticket(s)
DIG-1117

## Description
Adds a new page for ingest to the data portal.
TO BE COMPLETED:
- Adds a page to specify permissions for the OPA dataset
- Adds a clinical ingest page
- Adds a genomic ingest page
- Connects with the ingest microservice (https://github.com/CanDIG/candigv2-ingest)

## Expected Behaviour

Using the new ingest page, users should be able to create a new OPA dataset with a list of authorized users for read access, upload a single-cohort JSON file for validation and ingest to this dataset, and add genomic data as well.

## Screenshots (if appropriate)
### Before PR

### After PR

## Types of Change(s)
- [ ] 🪲 Bug fix (non-breaking change that fixes an issue)
- [ x ] ✨ New feature (non-breaking change that adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

## Has it been tested for:
- [ x ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] Prettier linter doesn't return errors
- [ ] Production branch PR browser testing: Chrome, Firefox, Edge, etc. 
- [ ] Locally tested
- [ ] Dev server tested
- [ ] Production tested when merging into stable/production branch

2023-08-10 18:30 UTC, OrdiNeu requested changes
Couple of code style changes below. Looks good otherwise though. :heavy_check_mark:

2023-08-10 18:30 UTC, OrdiNeu commented on package-lock.json
> +                "js-cookie": "^3.0.5",
```suggestion
```
Per Son's concerns that cookies are disabled in Safari by default, we're removing js-cookie (and cookies in general) in favor of local storage.

2023-08-10 18:30 UTC, OrdiNeu commented on package-lock.json
> +        },
```suggestion
```

2023-08-10 18:30 UTC, OrdiNeu commented on package-lock.json
> +        },
```suggestion
```

2023-08-10 18:30 UTC, OrdiNeu commented on src/ui-component/ingest/IngestTab.js
> +    }
This always returns one value -- is one or more of these supposed to be different?

2023-08-10 18:30 UTC, OrdiNeu commented on src/ui-component/ingest/IngestTab.js
> +                            background: idx === value ? '#FFFFFF' : '#F4FAFF'
Makes more sense here to have two styles classes and switch between them depending on `idx === value`.

2023-08-10 18:30 UTC, OrdiNeu commented on src/views/ingest/ingest.js
> +            <Grid item sx={{ background: 'white' }} className={classes.container}>
Better to put background: 'white' in the container class, here, unless there's something later on you need to reuse the class for (with a non-white background).

2023-08-10 18:30 UTC, OrdiNeu commented on src/ui-component/ingest/IngestTab.js
> +    };
Looks unnecessary (could just have an arrow function in Tabs' onChange), unless you were planning on adding more when the tab changes.

2023-08-10 18:30 UTC, OrdiNeu commented on src/ui-component/ingest/IngestTab.js
> +export default function IngestMenu() {
Your function is the whole IngestMenu, but the file name is just the IngestTab -- might want to either split this up into two files or edit the filename so it's clear (remember that `export default` means that they will be calling it via `import IngestTab from 'ui-component/ingest/IngestTab.js'`, so it looks like it's the tab and not the menu)

2023-08-10 18:30 UTC, OrdiNeu commented on src/ui-component/ingest/IngestTab.js
> +export default function IngestMenu() {
Also it's more common to define the function and then export default afterwards, as we often use PropTypes to help inform the IDE what props are meant to be passed.

2023-08-10 18:33 UTC, justin-ys commented on src/ui-component/ingest/IngestTab.js
> +    }
This is just filler

2023-10-25 15:26 UTC, OrdiNeu commented
NB: The old (pre-rebase) version is now stored at `custodian-page-backup`, in case my rebase broke anything

2023-10-25 15:38 UTC, OrdiNeu approved these changes

2023-10-25 16:22 UTC, merged